services:
  - type: web
    name: tourgenie-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 3000
      - key: API_KEY
        sync: false
